//
// Created by dylan on 17/04/2017.
//

#ifndef SNAKES_GAMESETTINGS_H
#define SNAKES_GAMESETTINGS_H

#define DEFAULT_START_DIRECTION D_UP
#define DEFAULT_START_SIZE 1

#define HOST_START_GAME_DELAY 2000000

#define MAXIMUM_FOOD_INTERVAL_SECS_US 3000000
#define MINIMUM_FOOD_INTERVAL_SECS_US 1000000
// Set NULL for no limit
#define MAXIMUM_AMOUNT_OF_FOOD 20
#endif //SNAKES_GAMESETTINGS_H
