//
// Created by dylan on 17/04/2017.
//

#ifndef SNAKES_GAMESETTINGS_H
#define SNAKES_GAMESETTINGS_H

#define DEFAULT_START_DIRECTION D_UP
#define DEFAULT_START_DIRECTION_KEY 'w'
#define DEFAULT_START_SIZE 3

#define MAXIMUM_FOOD_INTERVAL_SECS_US 3000000
#define MINIMUM_FOOD_INTERVAL_SECS_US 1000000
// Set 0 for no limit
#define MAXIMUM_AMOUNT_OF_FOOD_ON_SCREEN 20

#define FOOD_TO_WIN 15

#define GAME_UPDATE_RATE_US 160000

#define GAME_READ_USER_INPUT_UPDATE_RATE_US 150000

// All consoles will have the same size of the map
#define MAIN_WINDOW_ROW 80
#define MAIN_WINDOW_COLUMN 100

#define PROMPT_SCREEN_DELAY_SEC 2

#define HALF_DELAY_GET_CHAR_IN_TENTH_OF_A_SEC 5

#endif //SNAKES_GAMESETTINGS_H
